### ISSUE TITLE
Cannot find module 'react/lib/emptyFunction' when using react 0.14.0

### ISSUE THREAD

**Issue by tom-james-watson** [STRML/react-grid-layout#117]
When I attempt to use this package with react 0.14.0 I get the following error on compile:

```
Error: Cannot find module 'react/lib/emptyFunction' from '<redacted>/node_modules/react-grid-layout/node_modules/react-resizable/node_modules/react-draggable/lib'
```

**Comment by tony99nyr** [comment]
I am seeing this too.  It is the only item blocking me from upgrading to 0.14  It is due to react-draggable.  See https://github.com/mzabriskie/react-draggable/pull/102

**Comment by STRML** [comment]
This should be fixed in the fork of react-draggable. RGL will be moving to mainline react-draggable in the next release, `0.10`.

To recap, use `0.8.5`. `0.9.x` was buggy and will be abandoned. `0.10` will be the next stable release.

**Comment by tom-james-watson** [comment]
I am using 0.8.5 and this is happening still. Are you saying that it shouldn't be?

**Comment by STRML** [comment]
It should not, if you delete the package and reinstall.

**Comment by NoahMarconi** [comment]
`"react-grid-layout": "^0.8.5"` does not work with `"react": "^0.14.0"` after deleting and reinstalling all packages.

**Comment by tom-james-watson** [comment]
I can confirm what Noah said

**Comment by entotsu** [comment]
+1

**Comment by maitriyogin** [comment]
same here

**Comment by tom-james-watson** [comment]
Can we reopen this issue, please? Is there a quick fix that somebody can make in a fork, or a RC version of 0.10?

Alternatively, if anyone knows of any similar libraries that work with 0.14.0 then that would be great, too.

**Comment by STRML** [comment]
I will be updating the lib shortly now that I've finished react-draggable
1.0.

**Comment by XYZ-123** [comment]
temporary solution would be replacing in your node_modules all require('emptyFunction') to require('fbjs/lib/emptyFunction'). But thats just for your local env for sure. Waiting on the fix

**Comment by XYZ-123** [comment]
By the way have you considered switching to https://github.com/gaearon/react-dnd instead of react-draggable?

**Comment by maitriyogin** [comment]
not really, I was more interested in the combination of grid layout and DnD, I'll take a look.
I can wait a while, so it's not a huge problem.
/Stephen.

**Comment by clearbucketLabs** [comment]
@STRML problem is the react-sizable's dependacy on react-draggable is a different version, so we get two of em....

**Comment by maitriyogin** [comment]
hmm,ok so there needs to be some harmony between sizable and react-grid? Is it something we can try fixing or I guess we should hang on for a fix,
/stephen

**Comment by clearbucketLabs** [comment]
the react-sizable had a slightly older version (as per package.json), if you copy the draggable in react-grid-layout/node_modules to react-grid-layout/node_modules/react-resizable/node_modules/  and overwrite the older one it should be good.

**Comment by gravitypersists** [comment]
please fix this issue!

**Comment by dmr** [comment]
@STRML what can I do to help with version 1.0.0? We really need a new version of react-grid-layout

**Comment by tUrG0n** [comment]
+1 this plugin is simply non functional without this issue fixed :(

**Comment by tUrG0n** [comment]
FYI, I found a temporary fix.
Under `node_modules/react-resizable` dir, remove the line
```
    "react-draggable": "git+https://github.com/strml/react-draggable.git#v0.3.1"
```

from the `package.json` file, then do: `npm install react-draggable --save`.

This should install the latest version of draggable instead of v0.3.

Hope that helps.

**Comment by duknic** [comment]
Thanks tUrG0n, that does sidestep this issue, but I think this Draggable version causes me to bump into a problem noted in [Issue 79](https://github.com/STRML/react-grid-layout/issues/79), where resizing components causes them to jump immediately to an enormous size :). Has anyone else observed this behaviour?

**Comment by maitriyogin** [comment]
Hi Guys,
I just can't seem to get this to work in the gui..
What I'v done is 
1. npm install react-grid-layout
2. removed draggable from node_modules/react-grid-layout/node_modules/react-resizable/package.json
3. also removed node_modules/react-grid-layout/node_modules/react-resizable/node_modules/react-draggable
4. then npm install react-draggable
5. now everything build ok but when I view the result all the divs/cards are stacked onto of each other.

I'v tried this with the basic example in your repo ...

Any ideas?
/Stephen.
```
export class GridStuff extends React.Component {

  constructor(props) {
    super(props);
    this.state =  {grid : {
      className: 'layout',
      items: 20,
      rowHeight: 30,
      cols: 12
    } };
    this.state['layout'] = this.generateLayout() ;
  }

  generateDOM() {
    return _.map(_.range(this.state.grid.items), function(i) {
      return (<div key={i}><span className='text'>{i}</span></div>);
    });
  }

  generateLayout() {
    let p = this.state.grid;
    return _.map(new Array(p.items), function(item, i) {
      var y = _.result(p, 'y') || Math.ceil(Math.random() * 4) + 1;
      return {x: i * 2 % 12, y: Math.floor(i / 6) * y, w: 2, h: y, i: i};
    });
  }

  render() {
    return (
      <ReactGridLayout layout={this.state.layout}
        {...this.state.grid}>
        {this.generateDOM()}
      </ReactGridLayout>
    );
  }
}
```

**Comment by aweber1** [comment]
@duknic @maitriyogin hey guys, you might find this helpful: consider pulling the 'next' branch of react-grid-layout, which uses the latest versions of React, Draggable, and Resizable. Then take a look at the pull request I submitted for it: https://github.com/STRML/react-grid-layout/pull/128

This made the grid I'm working on functional in React 0.14. There may still be a few minor quirks to work out, but no show stoppers at this point (for me anyways).

hope it helps!

**Comment by STRML** [comment]
Adam - huge help by the way. I'm just waking up but will test your PR ASAP
and get a release out today.

**Comment by maitriyogin** [comment]
I love you and want to have your babies!!!
Huge mega thanks!
What an end to a panicky friday.
One glitch is that I have to clone and build and then include the dir in my package.json.
When I just include the branch theres no assets ... which is weird :+1: 
´´´
"react-grid-layout": "git+https://github.com/STRML/react-grid-layout.git#next",
´´´
Huge thanks!
/Stephen.

**Comment by akullpp** [comment]
Same here:

```
ERROR in ./~/react-grid-layout/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./build/ReactGridLayout in .../node_modules/react-grid-layout
 @ ./~/react-grid-layout/index.js 1:17-51

ERROR in ./~/react-grid-layout/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./build/ResponsiveReactGridLayout in .../node_modules/react-grid-layout
 @ ./~/react-grid-layout/index.js 2:28-72
```

**Comment by NeXTs** [comment]
Tha'ts because build forlder was not published to npm

**Comment by maitriyogin** [comment]
Hiya, having trouble with resize, doesn't seem to work ... and also drag seems to be a bit funky, in that theres an offset, probably about 200-300px ...
/Stephen.

**Comment by boyarskiy** [comment]
@STRML please update npm package. Because this bug doesn't fixed there yet.

**Comment by duknic** [comment]
@aweber1 
>This made the grid I'm working on functional in React 0.14. There may still be a few minor quirks to work out, but no show stoppers at this point (for me anyways).
Thanks so much for this, pulled _next_ branch and resizing now works great but I'm getting some jittery behaviour on dragging, perhaps related to comment from @maitriyogin.

**Comment by tom-james-watson** [comment]
By the jittery behaviour do you mean like this https://github.com/STRML/react-grid-layout/issues/126 ?

**Comment by maitriyogin** [comment]
Hmm almost. 
In my case I have a sidebar at 20% of the screen width and then a content pane of 80%. My grid is 12 cols and I have three items on each row with a spread of 4...
So when I drag one it kind of jumps 200px to the right. If I drag all the way to the left it aligns with start left of the content.
So it seems that the sidebar is offsetting the drag position...
Super spooky.
I'll fiddle with setting a pixel width and also including the side bar in the grid.
/stephen

**Comment by tuckwat** [comment]
I haven't had time to play with it but excited to see progress!  I think I saw the same thing though, a good test case is to create a RGL on a page with this CSS:

```css
body{
   padding: 250px;
}
```

It looks like the position object passed into calcXY is being passed the global mouse x/y.

**Comment by STRML** [comment]
Yes, it appears this is still an issue - investigating.

**Comment by SvitlanaShepitsena** [comment]
components/ListensToWidth.js line 69
```javascript
   _react.createElement
   instead of React.createElement 
```
:smirk:

**Comment by maitriyogin** [comment]
hiya, I'm probably doing something wrong in my package.json but when I include the next branch 
```
"react-grid-layout":"https://github.com/STRML/react-grid-layout.git#next",
```
I don't get the lib dir ...
I'm having to clone manually and build.
Any suggestions?
/Stephen.

**Comment by kaspyyy** [comment]
@maitriyogin dunno if you've solved this yet, but getting the next branch with 
`npm install react-grid-layout@0.10.0-beta1 --save`
fixes this in the short term.
